name: build

on:
  push:
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md
  workflow_dispatch:
  schedule:
    - cron: '30 03 01 */3 *' # Artifacts expire every 3 months

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          
        sm_version:
          - "1.9"
          - "1.10"
          - "1.11"
          - "latest"
          
        include:
          # Use MM:Source 1.11 as base version
          - meta_version: "1.11"
            meta_branch: "1.11-dev"
            
          - sm_version: latest
            sm_branch: master
            meta_version: latest
            meta_branch: master
          
          - sm_version: "1.9"
            sm_branch: "1.9-dev"
          
          - sm_version: "1.10"
            sm_branch: "1.10-dev"
          
          - sm_version: "1.11"
            sm_branch: "1.11-dev"
          
          - os: ubuntu-latest
            os_short: linux
          
          - os: windows-latest
            os_short: win
            
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          
      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x86 -host_arch=x64
          )
          
          :: Loop over all environment variables and make them global.
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo>>"%GITHUB_ENV%" %%a=%%b
          )
          
      - name: Getting SourceMod ${{ matrix.sm_version }}
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive
          
      - name: Getting MM:Source ${{ matrix.meta_version }}
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.meta_branch }}
          path: metamod-${{ matrix.meta_version }}
          
      - name: Getting AMBuild
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/ambuild
          path: ambuild
          
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Getting ambuild
        run: |
          python -m pip install wheel
          pip install git+https://github.com/alliedmodders/ambuild
          
      - name: Getting hl2sdk-l4d2
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: hl2sdk-l4d2
          
      - name: Getting own repository
        uses: actions/checkout@v3
        with:
          path: src
          
      - name: Compiling ${{ github.event.repository.name }} files
        shell: bash
        working-directory: src
        run: |
          mkdir build
          cd build
          python \
            ../configure.py \
            --enable-optimize \
            --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}"\
            --mms-path="${{ github.workspace }}/metamod-${{ matrix.meta_version }}"\
            --sdks=l4d2
          ambuild
          
      - name: Uploading package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: src/build/package
